Repository openthread/ot-commissioner, pull requests merged in 2020-03, with the labels that each got.

#20 [test] fix integration test
  tests/integration/bootstrap.sh
Labels: p0

#21 [code] apply constexpr to more constants
  include/commissioner/network_data.hpp
  src/library/network_data.cpp
Labels: enhancement

#19 [script] install latest CMake with pip
  .travis/script.sh
  script/bootstrap.sh
Labels: enhancement

#22 [build] allow downstream to change the default build flags
  CMakeLists.txt
Labels: enhancement

#23 [build] add headers and cmake and allow shared lib
  src/library/CMakeLists.txt
Labels: enhancement

#25 [tests] enhance integration test setup for OTBR
  tests/integration/bootstrap.sh
  tests/integration/common.sh
  tests/integration/run_tests.sh
Labels: enhancement

#35 [code] avoid static objects with non-trivial destructor
  src/app/cli/interpreter.cpp
  src/app/cli/interpreter.hpp
  src/library/uri.hpp
Labels: enhancement

#38 [script] sync make-pretty scripts from openthread
  .travis.yml
  .travis/script.sh
  CONTRIBUTING.md
  script/clang-format
  script/clang-format-check
  script/make-pretty
  tools/commissioner_thci/commissioner.py
  tools/commissioner_thci/commissioner_ctl.py
  tools/commissioner_thci/commissioner_impl.py
  tools/commissioner_thci/commissionerd.py
  tools/commissioner_thci/example_send_mlr.py
Labels: enhancement, p4

#26 [script] apply suggestions by shellcheck
  .travis/script.sh
  script/bootstrap.sh
  tests/integration/bootstrap.sh
  tests/integration/common.sh
  tests/integration/run_tests.sh
  tests/integration/test_announce_begin.sh
  tests/integration/test_discover.sh
  tests/integration/test_energy_scan.sh
  tests/integration/test_joining.sh
  tests/integration/test_operational_dataset.sh
  tests/integration/test_pan_id_query.sh
  tests/integration/test_petition.sh
Labels: enhancement

#36 [petition] return ID of existing active commissioner if one exists
  include/commissioner/commissioner.hpp
  include/commissioner/error.hpp
  src/app/cli/interpreter.cpp
  src/app/commissioner_app.cpp
  src/app/commissioner_app.hpp
  src/library/commissioner_impl.cpp
  src/library/commissioner_impl.hpp
  src/library/commissioner_safe.cpp
  src/library/commissioner_safe.hpp
  tests/unit/test_commissioner_impl.cpp
Labels: enhancement

#39 [log] add compile-time variadic arguments checking
  .travis.yml
  .travis/after_success.sh
  .travis/script.sh
  src/library/coap.cpp
  src/library/logging.cpp
  src/library/logging.hpp
Labels: bug

#48 [build] fix linking and installing shared libraries
  .travis.yml
  .travis/script.sh
  src/app/CMakeLists.txt
  src/common/CMakeLists.txt
  src/library/CMakeLists.txt
  tests/integration/common.sh
  tests/unit/CMakeLists.txt
  third_party/CMakeLists.txt
Labels: bug, p1

#50 [network-data] fix bit mask
  include/commissioner/network_data.hpp
Labels: bug

#49 [script] install cmake dependencies
  script/bootstrap.sh
Labels: enhancement
