Repository openthread/ot-commissioner, pull requests merged in 2020-10, with the labels that each got.

#147 [clang-format] update to clang-format-10
  .clang-format
  .github/workflows/build.yml
  CONTRIBUTING.md
  script/bootstrap.sh
  script/clang-format
Labels: continuous-integration, enhancement, p4

#149 [library] fix commissioner state when sending keep-alive failed
  src/library/commissioner_impl.cpp
Labels: bug

#151 [swig] map Java byte to uin8_t for only the ByteArray class
  src/java/commissioner.i
Labels: enhancement, p0

#152 [scripts] misc fixes in bootstrap script
  .github/workflows/build.yml
  include/commissioner/defines.hpp
  include/commissioner/network_data.hpp
  script/bootstrap.sh
  src/java/CMakeLists.txt
  src/java/commissioner.i
Labels: enhancement
