Repository openthread/ot-commissioner, pull requests merged in 2020-07, with the labels that each got.

#123 [test] enable custom OpenThread path
  tests/integration/bootstrap.sh
  tests/integration/common.sh
Labels: enhancement

#125 [test] use provided openthread repo for otbr
  tests/integration/bootstrap.sh
  tests/integration/common.sh
  tests/integration/test_announce_begin.sh
  tests/integration/test_cli.sh
  tests/integration/test_discover.sh
  tests/integration/test_energy_scan.sh
  tests/integration/test_joining.sh
  tests/integration/test_operational_dataset.sh
  tests/integration/test_pan_id_query.sh
  tests/integration/test_petition.sh
Labels: bug, continuous-integration

#112 [ccm] add compile-time option to exclude CCM features
  .github/workflows/tests.yml
  CMakeLists.txt
  src/library/CMakeLists.txt
  src/library/cbor.cpp
  src/library/commissioner_impl.cpp
  src/library/commissioner_impl.hpp
  src/library/cose.cpp
  src/library/cose.hpp
  src/library/cose_test.cpp
  src/library/cwt.hpp
  src/library/token_manager.cpp
  src/library/token_manager.hpp
  src/library/token_manager_test.cpp
  third_party/CMakeLists.txt
Labels: enhancement

#128 [event] fix ading user triggered events
  src/library/commissioner_safe.cpp
  src/library/joiner_session.cpp
  src/library/socket_test.cpp
Labels: bug

#127 [test] replace ot-br with ot-daemon in integration tests
  .github/workflows/tests.yml
  tests/integration/bootstrap.sh
  tests/integration/common.sh
  tests/integration/run_tests.sh
  tests/integration/test_announce_begin.sh
  tests/integration/test_cli.sh
  tests/integration/test_discover.sh
  tests/integration/test_energy_scan.sh
  tests/integration/test_joining.sh
  tests/integration/test_operational_dataset.sh
  tests/integration/test_pan_id_query.sh
  tests/integration/test_petition.sh
Labels: continuous-integration, enhancement

#138 [cli] fix signal handling
  src/app/cli/CMakeLists.txt
  src/app/cli/main.cpp
Labels: bug

#131 [tests] add unittests for common/utils.cpp
  src/common/CMakeLists.txt
  src/common/utils.hpp
  src/common/utils_test.cpp
  src/library/commissioner_impl.cpp
Labels: unittest
