Repository openthread/ot-commissioner, pull requests merged in 2020-04, with the labels that each got.

#33 [dtls] refine DTLS state and error handling
  src/library/coap_secure.hpp
  src/library/commissioning_session.cpp
  src/library/dtls.cpp
  src/library/dtls.hpp
Labels: enhancement

#34 [error] make error unignorable
  include/commissioner/defines.hpp
  include/commissioner/error.hpp
  src/app/commissioner_app.cpp
  src/app/json.cpp
  src/common/address.cpp
  src/common/address.hpp
  src/common/utils.hpp
  src/library/coap.cpp
  src/library/commissioner_impl.cpp
  src/library/commissioner_safe.cpp
  src/library/commissioning_session.cpp
  src/library/socket.cpp
  src/library/socket.hpp
  src/library/udp_proxy.cpp
  tests/unit/test_coap.cpp
  tests/unit/test_coap_secure.cpp
  tests/unit/test_cose.cpp
Labels: enhancement

#58 [config] comment out PSKc for default CCM config file
  src/app/etc/commissioner/ccm-config.json
Labels: enhancement

#62 [cli] fix help doc of the 'opdataset set securitypolicy' command
  src/app/cli/interpreter.cpp
Labels: documentation

#66 [build] add native cn-cbor library
  src/library/CMakeLists.txt
  tests/unit/CMakeLists.txt
  third_party/CMakeLists.txt
  third_party/cn-cbor/CMakeLists.txt
Labels: enhancement

#69 [cli] fix incomplete joiner command help doc
  src/app/cli/interpreter.cpp
Labels: documentation

#72 [doc] update stale cli readme
  src/app/cli/README.md
Labels: documentation

#76 [code] use nullptr instead of NULL
  src/library/cbor.hpp
  src/library/token_manager.cpp
Labels: enhancement

#53 [mdns] move mDNS out of the commissioner library
  include/commissioner/commissioner.hpp
  src/app/CMakeLists.txt
  src/app/border_agent.cpp
  src/app/border_agent.hpp
  src/app/cli/interpreter.cpp
  src/app/cli/interpreter.hpp
  src/app/commissioner_app.cpp
  src/app/commissioner_app.hpp
  src/library/CMakeLists.txt
  src/library/commissioner_impl.cpp
  src/library/commissioner_impl.hpp
  src/library/commissioner_safe.cpp
  src/library/commissioner_safe.hpp
  src/library/multicast_dns.cpp
  src/library/multicast_dns.hpp
  tests/integration/test_discover.sh
  tests/unit/test_commissioner_impl.cpp
Labels: enhancement

#73 [provisioning-url] move matching to application layer
  src/app/commissioner_app.cpp
  src/app/commissioner_app.hpp
  src/library/commissioning_session.cpp
Labels: enhancement

#75 [app] push Commissioner Dataset when connected
  src/app/cli/README.md
  src/app/cli/interpreter.cpp
  src/app/commissioner_app.cpp
  src/app/commissioner_app.hpp
  tests/integration/run_tests.sh
  tests/integration/test_cli.sh
Labels: enhancement

#83 [event-loop] break event loop from inside
  src/library/CMakeLists.txt
  src/library/commissioner_safe.cpp
  src/library/commissioner_safe.hpp
  src/library/commissioner_safe_test.cpp
Labels: bug

#88 [logging] make FileLogger thread safe
  src/app/file_logger.cpp
  src/app/file_logger.hpp
  src/app/json.cpp
Labels: enhancement

#93 [border-agent] fix format of TXT values in mDNS response
  src/app/border_agent.cpp
Labels: bug
