Repository openthread/ot-commissioner, pull requests merged in 2020-02, with the labels that each got.

#2 [tests] remove 1.2 CCM integration tests before dependencies becoming public
  README.md
  tests/integration/bootstrap.sh
  tests/integration/common.sh
  tests/integration/run_tests.sh
  tests/integration/test_bbr_dataset.sh
  tests/integration/test_ccm_ae_joining.sh
  tests/integration/test_ccm_nmkp_joining.sh
  tests/integration/test_ccm_petition.sh
  tests/integration/test_mlr.sh
Labels: enhancement

#3 [tools] fix Commissioner THCI dependency on pexpect
  tools/commissioner_thci/commissioner_impl.py
Labels: enhancement

#8 [app] fix destruction of commissioner app
  src/app/commissioner_app.cpp
  src/app/commissioner_app.hpp
Labels: bug

#15 [tests] update coverage
  .codecov.yml
  .travis/after_success.sh
  .travis/script.sh
  README.md
  src/CMakeLists.txt
  tests/CMakeLists.txt
Labels: enhancement

#14 [tools] add commissioner THCI fixes from IOP12 and latest tests
  tools/commissioner_thci/commissioner_impl.py
Labels: bug, p2

#11 [api] add commissioning handler
  include/commissioner/commissioner.hpp
  src/app/commissioner_app.cpp
  src/library/commissioner_impl.cpp
  src/library/commissioner_impl.hpp
  src/library/commissioner_safe.cpp
  src/library/commissioner_safe.hpp
  src/library/commissioning_session.cpp
Labels: enhancement

#16 [code] use enum class and some constexpr
  .gitignore
  include/commissioner/border_agent.hpp
  include/commissioner/commissioner.hpp
  include/commissioner/defines.hpp
  include/commissioner/network_data.hpp
  src/app/json.cpp
  src/library/commissioner_impl.cpp
  src/library/commissioner_impl.hpp
  src/library/commissioning_session.hpp
  src/library/cose.cpp
  src/library/dtls.hpp
  src/library/tlv.hpp
  tests/unit/test_coap_secure.cpp
  tests/unit/test_dtls.cpp
Labels: enhancement

#18 [build] add cmake option to disable building CLI App
  CMakeLists.txt
  src/CMakeLists.txt
Labels: enhancement
