Repository openthread/ot-commissioner, pull requests merged in 2021-04, with the labels that each got.

#185 [meshcop] use UDP proxy for MGMT commands
  include/commissioner/commissioner.hpp
  src/app/cli/interpreter.cpp
  src/app/commissioner_app.cpp
  src/app/commissioner_app.hpp
  src/library/commissioner_impl.cpp
  src/library/commissioner_impl.hpp
  src/library/commissioner_impl_test.cpp
  src/library/commissioner_safe.cpp
  src/library/commissioner_safe.hpp
Labels: cla: yes

#186 [dataset] fix and relax dataset response check
  src/library/commissioner_impl.cpp
Labels: bug, cla: yes

#187 [mgmt] send MGMT_COMMISSIONER_GET/SET.req with UDP proxy
  src/library/commissioner_impl.cpp
Labels: IOP, cla: yes

#184 [github-actions] add gcc-10 and clang-10,11 build tests
  .github/workflows/build.yml
Labels: cla: yes

#176 [coap] return unexpected coap response code as error
  include/commissioner/error.hpp
  src/common/error.cpp
  src/common/error_macros.hpp
  src/common/error_test.cpp
  src/library/coap.cpp
  src/library/coap.hpp
  src/library/commissioner_impl.cpp
  src/library/commissioner_impl.hpp
Labels: cla: yes, enhancement

#189 [bootstrap] add `brew update`
  script/bootstrap.sh
Labels: cla: yes, continuous-integration

#190 [coap] set request URI for only response message
  src/library/coap.cpp
  src/library/coap_test.cpp
Labels: bug, cla: yes

#196 [joiner-session] invoke "OnJoinerRequest" for the first joiner message
  src/library/commissioner_impl.cpp
Labels: cla: yes, enhancement

#194 [cmake] install with static library dependencies
  src/app/cli/CMakeLists.txt
  src/common/CMakeLists.txt
  src/library/CMakeLists.txt
Labels: bug, cla: yes

#191 [border-agent] use ephemeral port
  tests/integration/common.sh
  tests/integration/test_announce_begin.sh
  tests/integration/test_cli.sh
  tests/integration/test_energy_scan.sh
  tests/integration/test_joining.sh
  tests/integration/test_operational_dataset.sh
  tests/integration/test_pan_id_query.sh
  tests/integration/test_petition.sh
Labels: cla: yes, enhancement

#188 [udp-proxy] track Mesh-Local prefix in UDP Proxy client
  include/commissioner/commissioner.hpp
  include/commissioner/defines.hpp
  src/app/commissioner_app.cpp
  src/library/commissioner_impl.cpp
  src/library/commissioner_impl.hpp
  src/library/commissioner_safe.cpp
  src/library/commissioner_safe.hpp
  src/library/udp_proxy.cpp
  src/library/udp_proxy.hpp
Labels: IOP, cla: yes, enhancement

#183 [test] add timeout for calling ot-ctl
  tests/integration/common.sh
  tests/integration/run_tests.sh
Labels: cla: yes
