Repository openthread/ot-commissioner, pull requests merged in 2021-06, with the labels that each got.

#209 Merge cert to main
  src/library/commissioner_impl.cpp
  tools/commissioner_thci/commissioner.py
  tools/commissioner_thci/commissioner_impl.py
Labels: 1.2 certification, cla: yes, p1

#205 [thci] enhance for Thread 1.2
  tools/commissioner_thci/commissioner_impl.py
Labels: 1.2 certification, cla: yes, enhancement, p1

#211 [cli] fix "borderagent" command documentation
  src/app/cli/README.md
  src/app/commissioner_app.cpp
Labels: cla: yes, cli, documentation

#212 [dataset] avoid setting session ID or Border Agent Locator
  src/library/commissioner_impl.cpp
Labels: bug, cla: yes, p1
